<a href="https://colab.research.google.com/github/hhk54250/20MA573-HHK/blob/master/hw7/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:

%cd~

!git clone https://github.com/hhk54250/20MA573-HHK.git 
pass

%cd 20MA573-HHK/src/
%ls

from bsm import *

/root
fatal: destination path '20MA573-HHK' already exists and is not an empty directory.
/root/20MA573-HHK/src
bsm.py  optiondata.dat  prj01.ipynb  prj02.ipynb  __pycache__/


In [45]:
gbm = Gbm(init_state = 100., drift_ratio = .03, vol_ratio = .2)
option1 = VanillaOption(strike=97)
BS_price = gbm.bsm_price(option1)
print (BS_price)


11.014613780922488


In [61]:
import numpy as np
def S(x, drift):
  S = drift * x
  return S

def volatility(vol, x, gamma):
  volatility = vol * x**gamma
  return volatility

def eulerAp(
    x,T,N,vol,gamma,
    otype = 1,
    strike = 97):
  delta = T/N
  t = np.linspace(0, T, N+1)
  x_delta = []
  x_delta.append(x)

  drift = 0.03
  for i in range(N):
    Z = np.random.normal(0,1)
    x_delta.append(x_delta[i] + S(x,drift) * delta + volatility(vol, x, gamma) * np.sqrt(delta) * Z)
  price = max([0, (x_delta[N] - strike) * otype])
  return price

print(eulerAp(100,1,1000,0.2,1))

11.520978426915278


In [47]:
np_option_data1 = np.loadtxt('optiondata.dat', comments='#', delimiter=',')

print('>>>otype,>>>>>>> maturity, >>strike, >>>>>>option_price')
print(np_option_data1)

>>>otype,>>>>>>> maturity, >>strike, >>>>>>option_price
[[  1.           0.16666667  97.           5.32705461]
 [  1.           0.16666667  99.           3.86224255]
 [  1.           0.16666667 101.           2.7204371 ]
 [  1.           0.16666667 103.           2.1202793 ]
 [  1.           0.41666667  97.           7.23756307]
 [  1.           0.41666667  99.           5.95053461]
 [  1.           0.41666667 101.           5.2640122 ]
 [  1.           0.41666667 103.           4.97493422]]


In [48]:
opt_data = option_data1[4:8,]

def error_function(calpara):
  vol = calpara[0]
  elas = calpara[1]
  error = 0
  for i in np.arange(len(opt_data)):
    error += (opt_data[i, 3] - eulerAp(100, opt_data[i,1], 1000, vol, elas, opt_data[i, 0], opt_data[i,2]))**2    
  return error

init_guess = [.1, 1] 
print(">>> The calibrated volatility and elasticity constant respectively equals to ")
print(so.fmin(error_function, init_guess, disp = 0))



>>> The calibrated volatility and elasticity constant respectively equals to 
[0.09994141 1.00039063]
